before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: QE8JhczbeBvl2U0AeqS2NKKAyHy0nT5Ce4vhhIZWPXiV+NTUQJPIyiNuDvoXgGOaOwnujQQB8gcUgszANriUgXaMwqmvm5A3zESxdCZUedkWOwQWi1Yk3iJrXfGPDi61pDQsrgCdgVZyt3g+Xnx2SAANKGGuC7Z92rLWcqPxJaIZ6tnFR1+CPzAR4sMagYnSdlt5i8cpM/pT9DcfMCVZOSOGlOnWyx8mrUriWmC/qzP1JRG/tvJmVTypxCJPpv60dhY9tnsmgSi19jzFQEUpjBln+epcCXobytyd6DNXthLFOW7UsPtOS0zJnwZL0wrwmWVinQ3/Nfq4yhrytvji3XP8ElZyG1fq1y3lntg7QR4OpOA4PkGksbH1TDfDeKMn70sKOrasL4YCPnWWx6sGAnQ+JRPaBtIRkR5WCRVewb9lEtIug8BEgIeAHL8WCfH+hnB5/PU25VjD4WgNW+gj+wpAmZHQK1xqHcaOS2UjKZbmrd2sGT2h/g9F70PaYTFPrJ0xAJ2e1kggZ2kSFx0L6iTYb3EhlDqtL4ZEQjuXvqRF78mMTbcEguLuekCBGsvc1/F1nRe2P8mJHVOSvaKjZxru90/CxitqwXAzYXIandRXin9VUVNtvETs8Tipo64RQt21dNMhMEfFRxfRh4YQuUI45sb+7vtabSWfAW/sG74= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
